version: '3'

services:
  frontend:
    build: frontend
    ports:
      - 8501:8501
    depends_on:
      - backend
    volumes:
        - ./models:/models
        - ./user_tests:/user_tests
  backend:
    build: backend
    ports:
      - 8080:8080
