version: '2.3'

services:
  frontend:
    build: frontend
    ports:
      - 8501:8501
    depends_on:
      - backend
  backend:
    build: backend
    ports:
      - 8084:8084
    runtime: nvidia
    volumes:
    - ./user_tests:/user_tests 
    - /usr/local/cuda:/usr/local/cuda
